steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/calculator-app/calculator-app-node:$COMMIT_SHA',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'australia-southeast1-docker.pkg.dev/$PROJECT_ID/calculator-app/calculator-app-node:$COMMIT_SHA'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'calculator-service-node',
      '--image', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/calculator-app/calculator-app-node:$COMMIT_SHA',
      '--region', 'australia-southeast1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/calculator-app/calculator-app-node:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
